### ISSUE TITLE
problem about multi_gpu flag

### ISSUE THREAD

**Issue by ley61** [deepmind/ferminet#4]
Dear authors~ It's really a great package and I enjoy much using it to study molecule properties.
However, I encounter a problem when I try to run this package on multi gpus. I follow the tutorial and install tensorflow-gpu just like the readme said "pip install -e'.[tensorflow-gpu]'.  Then I run "ferminet --multi_gpu True" in my terminal. The programs ends up with an error:"**ValueError: Variable KFAC/model/det_net/after_det_weights/replica_1/KFAC/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?**"
It seems the variables have scope problems when run on multi-gpus. But it works well on one gpu. I also contact my colleagues and they all have this problem. 
Can you told me how to fix it. Thanks!

**Comment by jsspencer** [comment]
Please try patching the tensorflow code.

In `tensorflow_core/python/training/slot_creator.py` (inside the virtualenv site-packages -- something like `/path/to/venv/lib/python3.7/site-packages/tensorflow_core/python/training/slot_creator.py`), there are two functions, `create_slot` and `create_slot_with_initializer`, which contain the test

```
 if context.executing_eagerly():
  prefix = primary._shared_name
else:
  prefix = primary.op.name
```

Change the if statement to:

```
if isinstance(primary, variables.Variable):
   ...
```

This matches the upstream code (which didn't get released in TF 1.15) in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/slot_creator.py. The commit which fixed this issue is https://github.com/tensorflow/tensorflow/commit/3a22ef3c8a466123d60c1a5d10d62e4d2d0f92d2. I'll try to get this backported to the 1.15 release series.

(I believe that this problem only affects using K-FAC -- using ADAM should work fine with multiple GPUs)

**Comment by ley61** [comment]
Thank you so much so such a quick and detailed reply!  I will try immediately.

**Comment by ley61** [comment]
Thank you so much for such a quick and detailed reply! I will try immediately.
